"""
DocMax Watch Mode
Monitors a directory for new files and automatically processes them.
"""

from __future__ import annotations

import time
from pathlib import Path

from docmax.utils import abort, console, info, success, warn
from docmax.config import (
    DEFAULT_OCR_LANG,
    SUPPORTED_IMAGE_EXTS,
    SUPPORTED_PDF_EXTS,
    WATCH_DEBOUNCE_SECONDS,
)


# ---------------------------------------------------------------------------
# Event handler
# ---------------------------------------------------------------------------

class _DocMaxHandler:
    """Handles file-system events and dispatches to the correct action."""

    def __init__(self, action: str, lang: str, fmt: str):
        self.action = action
        self.lang = lang
        self.fmt = fmt
        self._seen: set = set()

    def dispatch(self, path: Path) -> None:

        # Avoid duplicate events
        if path in self._seen:
            return

        self._seen.add(path)

        # Wait for file to finish writing
        time.sleep(WATCH_DEBOUNCE_SECONDS)

        if not path.exists():
            return

        ext = path.suffix.lower()

        # Ignore DocMax-generated files
        generated_suffixes = (
            "_searchable",
            "_compressed",
            "_ocr",
            "_processed",
        )

        # Ignore files generated by DocMax itself

        if (
            path.stem.endswith("_compressed")
            or path.stem.endswith("_searchable")
            or path.stem.endswith("_ocr")
            or path.stem.endswith("_processed")
        ):
            return

        # -----------------------------------------------------
        # Determine allowed extensions for each action
        # -----------------------------------------------------

        if self.action == "ocr":
            allowed = SUPPORTED_IMAGE_EXTS | {".pdf"}

        elif self.action == "searchable":
            allowed = {".pdf"}

        elif self.action == "compress":
            allowed = {".pdf"}

        elif self.action == "preprocess":
            allowed = SUPPORTED_IMAGE_EXTS

        else:
            warn(f"Unknown watch action: {self.action}")
            return

        # Ignore unsupported files completely
        if ext not in allowed:
            return

        console.print(
            f"\n[bold cyan]-> Detected:[/bold cyan] {path.name}"
        )

        try:

            if self.action == "ocr":

                from docmax.engine import ocr_pdf, ocr_image

                if ext == ".pdf":
                    ocr_pdf(
                        path,
                        lang=self.lang,
                        fmt=self.fmt
                    )
                else:
                    ocr_image(
                        path,
                        lang=self.lang,
                        fmt=self.fmt
                    )

            elif self.action == "searchable":

                from docmax.engine import make_searchable_pdf

                make_searchable_pdf(
                    path,
                    lang=self.lang
                )

            elif self.action == "compress":

                from docmax.operations import compress

                compress(path)

            elif self.action == "preprocess":

                from docmax.processor import preprocess_for_ocr

                preprocess_for_ocr(path)

        except Exception as exc:

            console.print(
                f"[red]Error processing {path.name}:[/red] {exc}"
            )

# ---------------------------------------------------------------------------
# Watch entry point
# ---------------------------------------------------------------------------

def watch(
    directory: Path,
    action: str = "ocr",
    lang: str = DEFAULT_OCR_LANG,
    fmt: str = "txt",
) -> None:
    """
    Monitor a directory and process new files automatically.

    action: ocr | searchable | compress | preprocess
    """
    try:
        from watchdog.observers import Observer
        from watchdog.events import FileSystemEventHandler
    except ImportError:
        abort("watchdog is required. Run: pip install watchdog")

    if not directory.exists():
        abort(f"Directory not found: {directory}")

    handler_state = _DocMaxHandler(action=action, lang=lang, fmt=fmt)

    class _WatchdogBridge(FileSystemEventHandler):
        def on_created(self, event):
            print("CREATED EVENT:", event.src_path)

            if not event.is_directory:
                handler_state.dispatch(Path(event.src_path))

        def on_moved(self, event):
            print("MOVED EVENT:", event.dest_path)
            if not event.is_directory:
                handler_state.dispatch(Path(event.dest_path))

    observer = Observer()
    observer.schedule(_WatchdogBridge(), str(directory), recursive=True)
    observer.start()

    console.print(
        f"\n[bold green]Watching[/bold green] [bold]{directory}[/bold] "
        f"for new files (action: [cyan]{action}[/cyan])\n"
        "[dim]Press Ctrl+C to stop.[/dim]\n"
    )

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
        info("Watch mode stopped.")

    observer.join()
